# Generated by Django 4.2.5 on 2025-01-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Name',
            field=models.TextField(default='Name'),
            preserve_default=False,
        ),
    ]
